//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./grammars/Language.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace analyzer {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LanguageParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILanguageVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LanguageParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.declaraciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaraciones([NotNull] LanguageParser.DeclaracionesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrimeraDecl</c>
	/// labeled alternative in <see cref="LanguageParser.declararvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimeraDecl([NotNull] LanguageParser.PrimeraDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SegundaDecl</c>
	/// labeled alternative in <see cref="LanguageParser.declararvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegundaDecl([NotNull] LanguageParser.SegundaDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SliceIniciali</c>
	/// labeled alternative in <see cref="LanguageParser.declararvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceIniciali([NotNull] LanguageParser.SliceInicialiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SliceNoIncial</c>
	/// labeled alternative in <see cref="LanguageParser.declararvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceNoIncial([NotNull] LanguageParser.SliceNoIncialContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Matris</c>
	/// labeled alternative in <see cref="LanguageParser.declararvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatris([NotNull] LanguageParser.MatrisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StructParam</c>
	/// labeled alternative in <see cref="LanguageParser.declararvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructParam([NotNull] LanguageParser.StructParamContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReasignarSlice</c>
	/// labeled alternative in <see cref="LanguageParser.declararvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReasignarSlice([NotNull] LanguageParser.ReasignarSliceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.datos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatos([NotNull] LanguageParser.DatosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.filasMatriz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilasMatriz([NotNull] LanguageParser.FilasMatrizContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.filaMatriz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilaMatriz([NotNull] LanguageParser.FilaMatrizContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.instStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstStruct([NotNull] LanguageParser.InstStructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.listaAtributos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListaAtributos([NotNull] LanguageParser.ListaAtributosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncDcl1</c>
	/// labeled alternative in <see cref="LanguageParser.funcDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDcl1([NotNull] LanguageParser.FuncDcl1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncStruct</c>
	/// labeled alternative in <see cref="LanguageParser.funcDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncStruct([NotNull] LanguageParser.FuncStructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] LanguageParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpreStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpreStmt([NotNull] LanguageParser.ExpreStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrinStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrinStmt([NotNull] LanguageParser.PrinStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BloqueSente</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloqueSente([NotNull] LanguageParser.BloqueSenteContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SoloPasar</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoloPasar([NotNull] LanguageParser.SoloPasarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Ifstat</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstat([NotNull] LanguageParser.IfstatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InstrucSwitch</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrucSwitch([NotNull] LanguageParser.InstrucSwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WhileStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStmt([NotNull] LanguageParser.WhileStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStmt([NotNull] LanguageParser.ForStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForSlice</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForSlice([NotNull] LanguageParser.ForSliceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStmt([NotNull] LanguageParser.BreakStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStmt([NotNull] LanguageParser.ContinueStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] LanguageParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit([NotNull] LanguageParser.ForInitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InstrucCase</c>
	/// labeled alternative in <see cref="LanguageParser.instCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrucCase([NotNull] LanguageParser.InstrucCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InstrucDefault</c>
	/// labeled alternative in <see cref="LanguageParser.instDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrucDefault([NotNull] LanguageParser.InstrucDefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Asig_Aumento</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsig_Aumento([NotNull] LanguageParser.Asig_AumentoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Asig_Decre</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsig_Decre([NotNull] LanguageParser.Asig_DecreContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Aumento_Uno</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAumento_Uno([NotNull] LanguageParser.Aumento_UnoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Decreme_Uno</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecreme_Uno([NotNull] LanguageParser.Decreme_UnoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncAtoi</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncAtoi([NotNull] LanguageParser.FuncAtoiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncParFloat</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncParFloat([NotNull] LanguageParser.FuncParFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncTypeOf</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncTypeOf([NotNull] LanguageParser.FuncTypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncIndex</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncIndex([NotNull] LanguageParser.FuncIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncJoin</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncJoin([NotNull] LanguageParser.FuncJoinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncLen</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncLen([NotNull] LanguageParser.FuncLenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncAppend</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncAppend([NotNull] LanguageParser.FuncAppendContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignaList</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignaList([NotNull] LanguageParser.AsignaListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignaMatris</c>
	/// labeled alternative in <see cref="LanguageParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignaMatris([NotNull] LanguageParser.AsignaMatrisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Equalitys</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualitys([NotNull] LanguageParser.EqualitysContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LlamadaFuncio</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadaFuncio([NotNull] LanguageParser.LlamadaFuncioContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Or</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] LanguageParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDiv([NotNull] LanguageParser.MulDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] LanguageParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] LanguageParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TipoNil</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipoNil([NotNull] LanguageParser.TipoNilContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] LanguageParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ObtenerPos</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObtenerPos([NotNull] LanguageParser.ObtenerPosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Negacion</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegacion([NotNull] LanguageParser.NegacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifaider</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifaider([NotNull] LanguageParser.IdentifaiderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SumRes</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumRes([NotNull] LanguageParser.SumResContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Float</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat([NotNull] LanguageParser.FloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ObtenerMatris</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObtenerMatris([NotNull] LanguageParser.ObtenerMatrisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Asigna</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsigna([NotNull] LanguageParser.AsignaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Relacional</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelacional([NotNull] LanguageParser.RelacionalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>And</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] LanguageParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Assign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] LanguageParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Negar</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegar([NotNull] LanguageParser.NegarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] LanguageParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Rune</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRune([NotNull] LanguageParser.RuneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Llama</c>
	/// labeled alternative in <see cref="LanguageParser.llamada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlama([NotNull] LanguageParser.LlamaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Gets</c>
	/// labeled alternative in <see cref="LanguageParser.llamada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGets([NotNull] LanguageParser.GetsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] LanguageParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.booll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooll([NotNull] LanguageParser.BoollContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.tipos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipos([NotNull] LanguageParser.TiposContext context);
}
} // namespace analyzer
